#pragma once

// AUTO-GENERATED by tools/generate_bridge.py from bridges/telemetry.bridge.json
// DO NOT EDIT by hand. Regenerate with:
//   python tools/generate_bridge.py bridges/telemetry.bridge.json
//
// Lightweight metrics / event-counter bridge. Demonstrates the bridge codegen pipeline. Safe to delete in consumer projects.

#include <mitiru/cef/MitiruCefContext.hpp>

#include <nlohmann/json.hpp>

#include <functional>
#include <string>

namespace mitiru::cef::bridges
{

/// @brief Generated CEF bridge for `telemetry`. Bind callbacks then call registerOn().
class TelemetryBridge
{
public:
	using EmitFn = std::function<nlohmann::json(const std::string&, const double&)>;
	using SnapshotFn = std::function<nlohmann::json()>;
	using ResetFn = std::function<nlohmann::json()>;

	EmitFn onEmit;
	SnapshotFn onSnapshot;
	ResetFn onReset;

	void registerOn(MitiruCefContext& ctx)
	{
		ctx.registerHandler("telemetry.emit", [this](const std::string& payload) -> std::string { return _handleEmit(payload); });
		ctx.registerHandler("telemetry.snapshot", [this](const std::string& payload) -> std::string { return _handleSnapshot(payload); });
		ctx.registerHandler("telemetry.reset", [this](const std::string& payload) -> std::string { return _handleReset(payload); });
	}

private:
	std::string _handleEmit(const std::string& payload)
	{
		try
		{
			auto in = nlohmann::json::parse(payload);
			std::string event = in.at("event").get<std::string>();
			double value = in.value("value", 1.0);
			if (!onEmit) { return nlohmann::json{{"error", "onEmit not bound"}}.dump(); }
			nlohmann::json result = onEmit(event, value);
			return result.dump();
		}
		catch (const std::exception& e)
		{
			return nlohmann::json{{"error", e.what()}}.dump();
		}
	}

	std::string _handleSnapshot(const std::string& payload)
	{
		try
		{
			auto in = nlohmann::json::parse(payload);
			if (!onSnapshot) { return nlohmann::json{{"error", "onSnapshot not bound"}}.dump(); }
			nlohmann::json result = onSnapshot();
			return result.dump();
		}
		catch (const std::exception& e)
		{
			return nlohmann::json{{"error", e.what()}}.dump();
		}
	}

	std::string _handleReset(const std::string& payload)
	{
		try
		{
			auto in = nlohmann::json::parse(payload);
			if (!onReset) { return nlohmann::json{{"error", "onReset not bound"}}.dump(); }
			nlohmann::json result = onReset();
			return result.dump();
		}
		catch (const std::exception& e)
		{
			return nlohmann::json{{"error", e.what()}}.dump();
		}
	}
};

} // namespace mitiru::cef::bridges
