#pragma once

/// @file PackagingTool.hpp
/// @brief ゲームパッケージング・配布ツール
/// @details ゲームのビルド成果物とアセットをプラットフォーム別に
///          パッケージ化するための機能を提供する。
///          Windows (.exe + assets), Web (HTML + .wasm + .data) に対応。

#include <algorithm>
#include <chrono>
#include <cstdint>
#include <functional>
#include <sstream>
#include <string>
#include <vector>

namespace mitiru::resource
{

/// @brief ターゲットプラットフォーム
enum class TargetPlatform : uint8_t
{
	Windows = 0,  ///< Windows (.exe + assets)
	Web,          ///< Web (HTML + .wasm + .data)
};

/// @brief パッケージ設定
struct PackageConfig
{
	std::string gameName;                      ///< ゲーム名
	std::string version;                       ///< バージョン文字列（例: "1.0.0"）
	std::string assetsDir;                     ///< アセットディレクトリパス
	std::string outputDir;                     ///< 出力先ディレクトリパス
	TargetPlatform platform = TargetPlatform::Windows; ///< ターゲットプラットフォーム
	std::string iconPath;                      ///< アイコンファイルパス（オプション）
	bool includeDebugSymbols = false;          ///< デバッグシンボルを含めるか
};

/// @brief パッケージ内のファイルエントリ
struct PackageFileEntry
{
	std::string relativePath;   ///< パッケージ内の相対パス
	std::string sourcePath;     ///< ソースファイルの絶対パス
	uint64_t sizeBytes = 0;     ///< ファイルサイズ（バイト）
	std::string hash;           ///< SHA256ハッシュ（デルタ更新用）
};

/// @brief バージョンメタデータ
struct VersionMetadata
{
	std::string version;         ///< バージョン文字列
	std::string buildTimestamp;  ///< ビルド日時（ISO 8601）
	std::string gitHash;         ///< gitコミットハッシュ
	std::string platform;        ///< ターゲットプラットフォーム名
	bool debugBuild = false;     ///< デバッグビルドか
};

/// @brief パッケージング結果
struct PackageResult
{
	bool success = false;                         ///< 成功フラグ
	std::string outputPath;                       ///< 出力パス
	std::vector<PackageFileEntry> files;           ///< パッケージに含まれたファイル一覧
	VersionMetadata metadata;                      ///< バージョンメタデータ
	uint64_t totalSizeBytes = 0;                   ///< 合計サイズ（バイト）
	std::string errorMessage;                      ///< エラーメッセージ（失敗時）
};

/// @brief デルタ更新マニフェスト内のエントリ
struct DeltaEntry
{
	std::string relativePath;   ///< ファイルの相対パス
	std::string oldHash;        ///< 旧バージョンのハッシュ
	std::string newHash;        ///< 新バージョンのハッシュ
	uint64_t newSize = 0;       ///< 新バージョンのサイズ

	/// @brief 変更種別
	enum class ChangeType : uint8_t
	{
		Added = 0,    ///< 新規追加
		Modified,     ///< 変更
		Removed,      ///< 削除
	};

	ChangeType changeType = ChangeType::Modified; ///< 変更種別
};

/// @brief デルタ更新マニフェスト
struct DeltaManifest
{
	std::string fromVersion;              ///< 旧バージョン
	std::string toVersion;                ///< 新バージョン
	std::vector<DeltaEntry> entries;      ///< 変更ファイル一覧
	uint64_t totalDeltaSize = 0;          ///< デルタ合計サイズ（バイト）
};

/// @brief ゲームパッケージングツール
/// @details ゲームのビルド成果物とアセットをスキャンし、
///          プラットフォーム別のパッケージを生成する。
///          NSISインストーラースクリプトやWeb配布用HTMLも生成可能。
///
/// @code
/// mitiru::resource::PackagingTool tool;
/// PackageConfig config;
/// config.gameName = "MyGame";
/// config.version = "1.0.0";
/// config.assetsDir = "assets/";
/// config.outputDir = "dist/";
/// config.platform = TargetPlatform::Windows;
/// auto result = tool.createPackage(config);
/// @endcode
class PackagingTool
{
public:
	/// @brief パッケージを作成する
	/// @param config パッケージ設定
	/// @return パッケージング結果
	[[nodiscard]] PackageResult createPackage(const PackageConfig& config) const
	{
		PackageResult result;

		if (config.gameName.empty())
		{
			result.errorMessage = "gameName is required";
			return result;
		}
		if (config.assetsDir.empty())
		{
			result.errorMessage = "assetsDir is required";
			return result;
		}
		if (config.outputDir.empty())
		{
			result.errorMessage = "outputDir is required";
			return result;
		}

		// ファイルリスト生成
		result.files = generateFileList(config);

		// バージョンメタデータ生成
		result.metadata = generateMetadata(config);

		// 合計サイズ算出
		result.totalSizeBytes = 0;
		for (const auto& file : result.files)
		{
			result.totalSizeBytes += file.sizeBytes;
		}

		// プラットフォーム別出力パス
		switch (config.platform)
		{
		case TargetPlatform::Windows:
			result.outputPath = config.outputDir + "/" + config.gameName + "-" + config.version + "-win";
			break;
		case TargetPlatform::Web:
			result.outputPath = config.outputDir + "/" + config.gameName + "-" + config.version + "-web";
			break;
		}

		result.success = true;
		return result;
	}

	/// @brief Windowsインストーラー用NSISスクリプトを生成する
	/// @param config パッケージ設定
	/// @return NSISスクリプト文字列
	[[nodiscard]] std::string createInstaller(const PackageConfig& config) const
	{
		std::ostringstream nsis;
		nsis << "; NSIS Installer Script for " << config.gameName << "\n";
		nsis << "; Auto-generated by MitiruEngine PackagingTool\n\n";
		nsis << "!define PRODUCT_NAME \"" << config.gameName << "\"\n";
		nsis << "!define PRODUCT_VERSION \"" << config.version << "\"\n\n";
		nsis << "Name \"${PRODUCT_NAME} ${PRODUCT_VERSION}\"\n";
		nsis << "OutFile \"" << config.gameName << "-" << config.version << "-setup.exe\"\n";
		nsis << "InstallDir \"$PROGRAMFILES\\${PRODUCT_NAME}\"\n\n";

		if (!config.iconPath.empty())
		{
			nsis << "Icon \"" << config.iconPath << "\"\n\n";
		}

		nsis << "Section \"Install\"\n";
		nsis << "  SetOutPath $INSTDIR\n";
		nsis << "  File /r \"" << config.assetsDir << "\\*.*\"\n";
		nsis << "  File \"" << config.gameName << ".exe\"\n";
		nsis << "  CreateShortCut \"$DESKTOP\\${PRODUCT_NAME}.lnk\" \"$INSTDIR\\" << config.gameName << ".exe\"\n";
		nsis << "  WriteUninstaller \"$INSTDIR\\uninstall.exe\"\n";
		nsis << "SectionEnd\n\n";

		nsis << "Section \"Uninstall\"\n";
		nsis << "  Delete \"$DESKTOP\\${PRODUCT_NAME}.lnk\"\n";
		nsis << "  RMDir /r $INSTDIR\n";
		nsis << "SectionEnd\n";

		return nsis.str();
	}

	/// @brief Web配布用HTML + wasmファイル構成を生成する
	/// @param config パッケージ設定
	/// @return index.html の内容
	[[nodiscard]] std::string createWebDeploy(const PackageConfig& config) const
	{
		std::ostringstream html;
		html << "<!DOCTYPE html>\n";
		html << "<html lang=\"en\">\n";
		html << "<head>\n";
		html << "  <meta charset=\"UTF-8\">\n";
		html << "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
		html << "  <title>" << config.gameName << " " << config.version << "</title>\n";
		html << "  <style>\n";
		html << "    body { margin: 0; background: #000; display: flex; justify-content: center; align-items: center; height: 100vh; }\n";
		html << "    canvas { max-width: 100%; max-height: 100%; }\n";
		html << "    #loading { color: #fff; font-family: sans-serif; position: absolute; }\n";
		html << "  </style>\n";
		html << "</head>\n";
		html << "<body>\n";
		html << "  <div id=\"loading\">Loading...</div>\n";
		html << "  <canvas id=\"canvas\"></canvas>\n";
		html << "  <script>\n";
		html << "    var Module = {\n";
		html << "      canvas: document.getElementById('canvas'),\n";
		html << "      onRuntimeInitialized: function() {\n";
		html << "        document.getElementById('loading').style.display = 'none';\n";
		html << "      }\n";
		html << "    };\n";
		html << "  </script>\n";
		html << "  <script src=\"" << config.gameName << ".js\"></script>\n";
		html << "</body>\n";
		html << "</html>\n";

		return html.str();
	}

	/// @brief デルタ更新マニフェストを生成する
	/// @param oldFiles 旧バージョンのファイルリスト
	/// @param newFiles 新バージョンのファイルリスト
	/// @param fromVersion 旧バージョン文字列
	/// @param toVersion 新バージョン文字列
	/// @return デルタ更新マニフェスト
	[[nodiscard]] DeltaManifest createDeltaManifest(
		const std::vector<PackageFileEntry>& oldFiles,
		const std::vector<PackageFileEntry>& newFiles,
		const std::string& fromVersion,
		const std::string& toVersion) const
	{
		DeltaManifest manifest;
		manifest.fromVersion = fromVersion;
		manifest.toVersion = toVersion;
		manifest.totalDeltaSize = 0;

		// 旧ファイルをパスでインデックス化
		std::unordered_map<std::string, const PackageFileEntry*> oldMap;
		for (const auto& entry : oldFiles)
		{
			oldMap[entry.relativePath] = &entry;
		}

		// 新ファイルを走査して変更・追加を検出
		std::unordered_map<std::string, bool> processed;
		for (const auto& newEntry : newFiles)
		{
			processed[newEntry.relativePath] = true;
			const auto it = oldMap.find(newEntry.relativePath);

			if (it == oldMap.end())
			{
				// 新規追加
				DeltaEntry delta;
				delta.relativePath = newEntry.relativePath;
				delta.newHash = newEntry.hash;
				delta.newSize = newEntry.sizeBytes;
				delta.changeType = DeltaEntry::ChangeType::Added;
				manifest.totalDeltaSize += newEntry.sizeBytes;
				manifest.entries.push_back(std::move(delta));
			}
			else if (it->second->hash != newEntry.hash)
			{
				// 変更あり
				DeltaEntry delta;
				delta.relativePath = newEntry.relativePath;
				delta.oldHash = it->second->hash;
				delta.newHash = newEntry.hash;
				delta.newSize = newEntry.sizeBytes;
				delta.changeType = DeltaEntry::ChangeType::Modified;
				manifest.totalDeltaSize += newEntry.sizeBytes;
				manifest.entries.push_back(std::move(delta));
			}
		}

		// 旧バージョンにあって新バージョンにないファイルは削除
		for (const auto& oldEntry : oldFiles)
		{
			if (processed.find(oldEntry.relativePath) == processed.end())
			{
				DeltaEntry delta;
				delta.relativePath = oldEntry.relativePath;
				delta.oldHash = oldEntry.hash;
				delta.changeType = DeltaEntry::ChangeType::Removed;
				manifest.entries.push_back(std::move(delta));
			}
		}

		return manifest;
	}

private:
	/// @brief 設定からファイルリストを生成する
	/// @param config パッケージ設定
	/// @return ファイルエントリのベクタ
	/// @note 実際のファイルシステム走査はビルドツールに委譲。
	///       ここではエントリ構造の雛型を返す。
	[[nodiscard]] std::vector<PackageFileEntry> generateFileList(const PackageConfig& config) const
	{
		std::vector<PackageFileEntry> files;

		// メインバイナリ
		PackageFileEntry binary;
		switch (config.platform)
		{
		case TargetPlatform::Windows:
			binary.relativePath = config.gameName + ".exe";
			break;
		case TargetPlatform::Web:
			binary.relativePath = config.gameName + ".wasm";
			break;
		}
		binary.sourcePath = config.outputDir + "/" + binary.relativePath;
		files.push_back(std::move(binary));

		// Web向け追加ファイル
		if (config.platform == TargetPlatform::Web)
		{
			PackageFileEntry jsLoader;
			jsLoader.relativePath = config.gameName + ".js";
			jsLoader.sourcePath = config.outputDir + "/" + jsLoader.relativePath;
			files.push_back(std::move(jsLoader));

			PackageFileEntry dataFile;
			dataFile.relativePath = config.gameName + ".data";
			dataFile.sourcePath = config.outputDir + "/" + dataFile.relativePath;
			files.push_back(std::move(dataFile));
		}

		// デバッグシンボル
		if (config.includeDebugSymbols && config.platform == TargetPlatform::Windows)
		{
			PackageFileEntry pdb;
			pdb.relativePath = config.gameName + ".pdb";
			pdb.sourcePath = config.outputDir + "/" + pdb.relativePath;
			files.push_back(std::move(pdb));
		}

		return files;
	}

	/// @brief バージョンメタデータを生成する
	/// @param config パッケージ設定
	/// @return メタデータ
	[[nodiscard]] VersionMetadata generateMetadata(const PackageConfig& config) const
	{
		VersionMetadata meta;
		meta.version = config.version;
		meta.debugBuild = config.includeDebugSymbols;

		// ビルドタイムスタンプ（ISO 8601）
		const auto now = std::chrono::system_clock::now();
		const auto timeT = std::chrono::system_clock::to_time_t(now);
		char buf[32] = {};
		std::strftime(buf, sizeof(buf), "%Y-%m-%dT%H:%M:%SZ", std::gmtime(&timeT));
		meta.buildTimestamp = buf;

		switch (config.platform)
		{
		case TargetPlatform::Windows:
			meta.platform = "windows";
			break;
		case TargetPlatform::Web:
			meta.platform = "web";
			break;
		}

		// gitハッシュは外部から注入するか、ビルド時マクロで設定
#ifdef MITIRU_GIT_HASH
		meta.gitHash = MITIRU_GIT_HASH;
#else
		meta.gitHash = "unknown";
#endif

		return meta;
	}

	/// @brief unordered_mapヘルパー（ファイルリスト用）
	struct StringHash
	{
		using is_transparent = void;
		[[nodiscard]] std::size_t operator()(std::string_view sv) const noexcept
		{
			return std::hash<std::string_view>{}(sv);
		}
	};

	/// @brief unordered_mapの文字列透過比較
	using unordered_map = std::unordered_map<std::string, const PackageFileEntry*>;
};

} // namespace mitiru::resource
