/*!
 * mitiru_telemetry.js — AUTO-GENERATED by tools/generate_bridge.py
 * Source: bridges/telemetry.bridge.json
 * Regenerate with:
 *   python tools/generate_bridge.py bridges/telemetry.bridge.json
 *
 * Lightweight metrics / event-counter bridge. Demonstrates the bridge codegen pipeline. Safe to delete in consumer projects.
 *
 * Attaches to: window.mitiru.telemetry
 * Dispatch: mitiru.dispatch('telemetry.<method>', payload)
 *
 * To override JS fallback (e.g. for vitest or non-CEF builds):
 *   mitiru.telemetry._fallback.<method> = function(...args) { ... };
 */
(function(global)
{
	'use strict';

	const mitiru = global.mitiru = global.mitiru || {};
	if (mitiru.telemetry) { return; }  // already loaded

	const _fallback = {
		emit: function(event, value) { throw new Error('telemetry.emit: no JS fallback configured (override mitiru.telemetry._fallback.emit)'); },
		snapshot: function() { throw new Error('telemetry.snapshot: no JS fallback configured (override mitiru.telemetry._fallback.snapshot)'); },
		reset: function() { throw new Error('telemetry.reset: no JS fallback configured (override mitiru.telemetry._fallback.reset)'); }
	};

	const api = {};
	api._fallback = _fallback;

	api.emit = async function(event, value)
	{
		if (value === undefined) { value = 1; }
		if (typeof event !== 'string') { throw new TypeError('telemetry.emit: event must be string'); }
		if (value !== undefined && (typeof value !== 'number' || !Number.isFinite(value))) { throw new TypeError('telemetry.emit: value must be number'); }
		if (mitiru.dispatch)
		{
			try { return await mitiru.dispatch('telemetry.emit', { event, value }); }
			catch (_e) { /* fall through to JS fallback */ }
		}
		return _fallback.emit(event, value);
	};

	api.snapshot = async function()
	{
		if (mitiru.dispatch)
		{
			try { return await mitiru.dispatch('telemetry.snapshot', {}); }
			catch (_e) { /* fall through to JS fallback */ }
		}
		return _fallback.snapshot();
	};

	api.reset = async function()
	{
		if (mitiru.dispatch)
		{
			try { return await mitiru.dispatch('telemetry.reset', {}); }
			catch (_e) { /* fall through to JS fallback */ }
		}
		return _fallback.reset();
	};

	mitiru.telemetry = api;
})(typeof window !== 'undefined' ? window : globalThis);
